period = [17.0, 150.0]                       # minimum and maximum period in seconds
duration = [200.0, 288.0]                    # transient and stationary duration in minutes
nbands = 5                                   # number of bands to split frequency band

# event and station geographical weighting parameters
# [0]: condition number to determine reference distance
# [1]: minimum reference distance
# [2]: maximum reference distance
# [3]: maximum weighting ration (controlled by a damping term)
event_weighting = [0.33, 1.0, 4.0, 5.0]
station_weighting = [0.125, 0.5, 2.0, 5.0]
