[process]
period_min = 40.0                                # minimum period in seconds
period_max = 100.0                               # maximum period in seconds
duration = 200.0                                 # trace record length in minutes
duration_ft = 288.0                              # duration to determine frequency step in minutes
nbands = 5                                       # number of bands to split frequency band
dt = 1.6                                         # length of a time step
remove_response = [0.0075, 0.01, 0.0250, 0.0313] # pre-filter in remove_response
waterlevel = 100                                 # waterlevel in remove_response
taper = 5.0                                      # taper traces

[weight]
event_cond = 0.33                               # ratio of maximum condition number to determine reference distance
event_ref_dist_min = 1.0                        # minimum reference distance in degrees
event_ref_dist_max = 4.0                        # maximum reference distance in degrees
event_ratio_max = 5.0                           # maximum ratio between largest and smallest weight

station_cond = 0.125
station_ref_dist = [0.5, 2.0]
station_max_ratio = 5.0

[download]
gap = 10.0                                      # extra download duration before and after measured period in minutes
threads = 3                                     # number of simutaneous download threads

[download.restrictions]                         # parameters for obspy.clients.fdsn.mass_downloader.Restrictions
minimum_length = 0.3
location_priorities = ["", "00", "10"]
channel_priorities = ["BH[ZNE]", "HH[ZNE]"]
reject_channels_with_gaps = true

[window]
energy_threshold = 0.5
savefig = true

[window.flexwin.default]
# min and max period of seismograms
min_period = 40.0
max_period = 100.0

# STA/LAT water level
stalta_waterlevel = 0.085

# max tsfhit
tshift_acceptance_level = 16.0
tshift_reference = 0.0

# max amplitude difference
dlna_acceptance_level = 0.8
dlna_reference = 0.0

# min cc coef
cc_acceptance_level = 0.85

# window signal-to-noise ratio
s2n_limit = 3.0
s2n_limit_energy = 3.0
window_signal_to_noise_type = "amplitude"

# min/max surface wave velocity, to calculate slowest/fast
# surface wave arrival to define the boundaries of
# surface wave region
selection_mode = "body_and_mantle_waves"
min_surface_wave_velocity = 3.50
max_surface_wave_velocity = 4.10
earth_model = "ak135"
max_time_before_first_arrival = 100.0
max_time_after_last_arrival = 200.0

# check global data quality
check_global_data_quality = true
snr_integrate_base = 3.5
snr_max_base = 3.0

# see reference in FLEXWIN manual
c_0 = 0.7
c_1 = 3.0
c_2 = 0.0
c_3a = 1.0
c_3b = 2.0
c_4a = 3.0
c_4b = 10.0

# window merge strategy
resolution_strategy = "merge"

# #####################################################
# component specific settings
[window.flexwin.Z]
# Rayleigh wave
min_surface_wave_velocity = 3.50
max_surface_wave_velocity = 4.10

[window.flexwin.R]
# Rayleigh wave
min_surface_wave_velocity = 3.50
max_surface_wave_velocity = 4.10

 [window.flexwin.T]
# Love wave
min_surface_wave_velocity = 4.00
max_surface_wave_velocity = 4.80
