[processing]
period_min = 17.0                            # minimum period in seconds
period_max = 100.0                           # maximum period in seconds
duration = 200.0                             # trace record length in minutes
duration_ft = 288.0                          # duration to determine frequency step in minutes
nbands = 5                                   # number of bands to split frequency band
dt = 1.6                                     # length of a time step
remove_response = [0.008, 0.01, 0.0589, 0.0735]

[weighting]
event_cond = 0.33                            # ratio of maximum condition number to determine reference distance
event_ref_dist_min = 1.0                     # minimum reference distance in degrees
event_ref_dist_max = 4.0                     # maximum reference distance in degrees
event_ratio_max = 5.0                        # maximum ratio between largest and smallest weight

station_cond = 0.125
station_ref_dist = [0.5, 2.0]
station_max_ratio = 5.0

[download]
gap = 10.0                                   # extra download duration before and after measured period in minutes
threads = 3                                  # number of simutaneous download threads

[download.restrictions]                      # parameters for obspy.clients.fdsn.mass_downloader.Restrictions
minimum_length = 0.3
location_priorities = ["", "00", "10"]
channel_priorities = ["BH[ZNE]", "HH[ZNE]"]
reject_channels_with_gaps = true
