[process]
period_min = 40.0                                # minimum period in seconds
period_max = 100.0                               # maximum period in seconds
duration = 200.0                                 # trace record length in minutes
duration_ft = 288.0                              # duration to determine frequency step in minutes
nbands = 5                                       # number of bands to split frequency band
dt = 1.6                                         # length of a time step
remove_response = [0.0075, 0.01, 0.0250, 0.0313] # pre-filter in remove_response
waterlevel = 100                                 # waterlevel in remove_response
taper = 5.0                                      # taper traces

[weight]
event_cond = 0.33                               # ratio of maximum condition number to determine reference distance
event_ref_dist_min = 1.0                        # minimum reference distance in degrees
event_ref_dist_max = 4.0                        # maximum reference distance in degrees
event_ratio_max = 5.0                           # maximum ratio between largest and smallest weight

station_cond = 0.125
station_ref_dist = [0.5, 2.0]
station_max_ratio = 5.0

[download]
gap = 10.0                                      # extra download duration before and after measured period in minutes
threads = 3                                     # number of simutaneous download threads

[download.restrictions]                         # parameters for obspy.clients.fdsn.mass_downloader.Restrictions
minimum_length = 0.3
location_priorities = ["", "00", "10"]
channel_priorities = ["BH[ZNE]", "HH[ZNE]"]
reject_channels_with_gaps = true

[window]
energy_threshold = 0.5
savefig = true

[window.flexwin.Z]
tshift_acceptance_level = 18.0
tshift_reference = 0.0
dlna_acceptance_level = 0.8
dlna_reference = 0.0
std_ratio = 4.0
      
tshift_mean_range = [-5.0, 5.0]
tshift_std_level = 5.0
dlna_mean_range = [-1.0, 1.0]
dlna_std_level = 1.0

[window.flexwin.R]
tshift_acceptance_level = 18.0
tshift_reference = 0.0
dlna_acceptance_level = 0.8
dlna_reference = 0.0
std_ratio = 4.0
      
tshift_mean_range = [-5.0, 5.0]
tshift_std_level = 5.0
dlna_mean_range = [-1.0, 1.0]
dlna_std_level = 1.0

[window.flexwin.T]
tshift_acceptance_level = 18.0
tshift_reference = 0.0
dlna_acceptance_level = 0.8
dlna_reference = 0.0
std_ratio = 4.0
      
tshift_mean_range = [-5.0, 5.0]
tshift_std_level = 5.0
dlna_mean_range = [-1.0, 1.0]
dlna_std_level = 1.0
