period = [17.0, 150.0]                       # minimum and maximum period in seconds
duration = [120.0, 288.0]                    # transient and stationary duration in minutes
nbands = 5                                   # number of bands to split frequency band
download_gap = 10.0                          # additional time before and after measured period in minutes

# event and station geographical weighting parameters
# [0]: condition number to determine reference distance
# [1]: minimum reference distance
# [2]: maximum reference distance
# [3]: maximum weighting ration (controlled by a damping term)
event_weighting = [0.33, 1.0, 4.0, 5.0]
station_weighting = [0.125, 0.5, 2.0, 5.0]

# parameters for obspy.clients.fdsn.mass_downloader.Restrictions
[download]
minimum_length = 1.0
location_priorities = ["", "00", "10"]
channel_priorities = ["BH[ZNE]", "HH[ZNE]"]
reject_channels_with_gaps = true
