[job]
name = "sebox"                              # job name
nnodes = 2                                 # total number of nodes
account = "GEO111"                          # job account
walltime = 120.0                            # walltime to request
gap = 2.0                                   # terminate job before <gap> minutes before walltime runs out
debug = false                               # submit to debug queue
system = ['nnodes.job', 'Traverse']         # job scheduler

[root]
task = ['sebox.catalog', 'window']         # main task
np = 50
