# module configuration
module_system = "summit"
module_solver = "specfem"
module_kernel = "ortho"
module_optimizer = "gd"
module_search = "bracket"

# job configuration
job_name = "north"
job_nnodes = 64
job_account = "GEO111"
job_walltime = 120.0
job_gap = 2.0
job_debug = false

# main task
task = "kernel"
task_nnodes = 1

# path to external directories
path_mesh = "../mesh_m00_crust25"
path_mesh2 = "../mesh_m25"
path_specfem = "/gpfs/alpine/scratch/ccui/geo111/sf"
path_catalog = "/gpfs/alpine/scratch/ccui/geo111/north_syn"
path_adios = "/gpfs/alpine/scratch/ccui/geo111/wjbp"
path_model = "/gpfs/alpine/scratch/ccui/geo111/models/m00_crust25.bp"

# catalog
frequency_increment = 60
deglitch = [1, 200, 95]
measurement_threshold = 0
noise_threshold = 1e-8
event_weighting = [0.33, 1.0, 4.0, 5.0]
station_weighting = [0.125, 0.5, 2.0, 5.0]
remove_response = [0.00533, 0.00666, 0.0589, 0.0735]

# solver
duration = 300.0
transient_duration = 200.0
lddrk = false
catalog_boundary = [85.0, -115.0, 70.0, 90.0]
# catalog_boundary = [67.0, 91.0, 50.0, 90.0]

# kernel
dt = 0.16
unwrap_phase = false
period_range = [17.0, 150.0]
nkernels = 5
reference_velocity = 3.0
normalize_source = true
normalize_frequency = false
taper = 5.0
seed = 0
test_events = ['C201205242247A', 'C201904232015A']
test_bury = 0.0

# kernel processing
kernel_names = ['bulk_c_kl', 'bulk_betav_kl', 'bulk_betah_kl', 'eta_kl']
hessian_names = ['hess_kappa_kl', 'hess_mu_kl']
smooth_kernels = 120.0
smooth_hessian = 120.0
smooth_vertical = 1.0
smooth_with_prem = 0
fixed_preconditioner = false
precondition = 200.0
source_mask = true
test_encoding = true
save_vtu = ['bulk_betav_kl']

# misfit
phase_factor = 1.0
amplitude_factor = 0.0
double_difference = true

# optimization
niters = 50
nsteps = 5
step_init = 0.01
mem = 5
momentum = 0.1
