#!/usr/bin/env python
from sys import argv

from pypers import basedir as d


entries = d.ls()

if 'config.toml' in entries:
    for entry in entries:
        if entry != 'config.toml' and entry != 'job.bash' and entry not in argv:
            d.rm(entry)

else:
    print('config.toml not found')
